{
	"version": 1586396879,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"images/sensordestroi-sheet0.png",
		"images/itemazul-sheet0.png",
		"images/itemamarelo-sheet0.png",
		"images/botamarelo-sheet0.png",
		"images/btazul-sheet0.png",
		"images/tiledbackground2.png",
		"images/reiniciar-sheet0.png",
		"images/hp-sheet0.png",
		"images/fundo-sheet0.png",
		"images/sprite6-sheet0.png",
		"images/brvida-sheet0.png",
		"images/sensordestroif2-sheet0.png",
		"images/itemazulf2-sheet0.png",
		"images/itemamarelof2-sheet0.png",
		"images/bot2f2-sheet0.png",
		"images/sensordestroif23-sheet0.png",
		"images/botverde3-sheet0.png",
		"images/sensordestroif234-sheet0.png",
		"images/botazul34-sheet0.png",
		"images/tb10.png",
		"images/d10-sheet0.png",
		"images/i10-sheet0.png",
		"images/br10-sheet0.png",
		"images/f10-sheet0.png",
		"images/bo10-sheet0.png",
		"images/bfechar-sheet0.png",
		"images/d2-sheet0.png",
		"images/botpausajogof2-sheet0.png",
		"images/d3-sheet0.png",
		"images/sprite16-sheet0.png",
		"images/sprite15-sheet0.png",
		"images/sprite-sheet0.png",
		"images/sprite2-sheet0.png",
		"images/sprite4-sheet0.png",
		"images/sprite5-sheet0.png",
		"images/sprite7-sheet0.png",
		"images/sprite10-sheet0.png",
		"images/passainfo1-sheet0.png",
		"images/mp-sheet0.png",
		"images/sprite11-sheet0.png",
		"images/velhinhabemvindo-sheet0.png",
		"images/velhinhabemvindo-sheet1.png",
		"images/posru-sheet0.png",
		"images/negru-sheet0.png",
		"images/sprite17-sheet0.png",
		"images/sprite12-sheet0.png",
		"images/posapf-sheet0.png",
		"images/sprite19-sheet0.png",
		"images/sprite20-sheet0.png",
		"images/textoerro1-sheet0.png",
		"images/senhoraerro1-sheet0.png",
		"images/negaerro2-sheet0.png",
		"images/sprite33-sheet0.png",
		"images/sprite38-sheet0.png",
		"images/sprite3-sheet0.png",
		"images/sprite40-sheet0.png",
		"media/É a sua primeira vez aqui.ogg",
		"media/o mundo flarc foi pensado (mp3cut.net) (1).m4a",
		"media/o mundo flarc foi pensado (mp3cut.net) (1).ogg",
		"media/combinar a cor da cereja com a cor do bolinho (mp3cut.net).m4a",
		"media/combinar a cor da cereja com a cor do bolinho (mp3cut.net).ogg",
		"media/notei que não conseguiu concluir (mp3cut.net).m4a",
		"media/notei que não conseguiu concluir (mp3cut.net).ogg",
		"media/parabens foi um otimo trabalho vamos a mais uma pa (mp3cut.net).m4a",
		"media/parabens foi um otimo trabalho vamos a mais uma pa (mp3cut.net).ogg",
		"media/parabens, concluiu os desafios (mp3cut.net).m4a",
		"media/parabens, concluiu os desafios (mp3cut.net).ogg",
		"media/somdefundocordavez.m4a",
		"media/somdefundocordavez.ogg",
		"media/isso mesmo (mp3cut.net).m4a",
		"media/isso mesmo (mp3cut.net).ogg",
		"media/não não não (mp3cut.net).m4a",
		"media/não não não (mp3cut.net).ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}