{
	"version": 1586383714,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"images/mascara.png",
		"images/faixas-sheet0.png",
		"images/sprite2-sheet0.png",
		"images/sprite-sheet0.png",
		"images/tdestinoef1intro.png",
		"images/negmef1intro-sheet0.png",
		"images/posmef1intro-sheet0.png",
		"images/velhinhoerrof1intro-sheet0.png",
		"images/velhinhoerrof1intro-sheet1.png",
		"images/velhinhoerrof1intro-sheet2.png",
		"images/tiledbackground8.png",
		"images/vetorescentimetros-sheet0.png",
		"images/ihudopcoesf2-sheet0.png",
		"images/breiniciarf2-sheet0.png",
		"images/tiledbackgroundf2.png",
		"images/bfecharf2-sheet0.png",
		"images/objetocriadof2-sheet0.png",
		"images/fundojogof2.png",
		"images/bolhinhasestouradasf2.png",
		"images/fundoprogressotempof2-sheet0.png",
		"images/divisaohudjogof2-sheet0.png",
		"images/bgprogressof2.png",
		"images/botpausajogof2-sheet0.png",
		"images/bfechar-sheet0.png",
		"images/ihudpause-sheet0.png",
		"images/breiniciar-sheet0.png",
		"images/objetocriado-sheet0.png",
		"images/botpausa-sheet0.png",
		"images/voltaaojogo-sheet0.png",
		"images/negm-sheet0.png",
		"images/voltaaojogo2f2-sheet0.png",
		"images/d20-sheet0.png",
		"images/fundo-sheet0.png",
		"images/hp-sheet0.png",
		"images/sprite6-sheet0.png",
		"images/sprite5-sheet0.png",
		"images/sprite7-sheet0.png",
		"images/hp2-sheet0.png",
		"images/sprite12-sheet0.png",
		"images/brvida2-sheet0.png",
		"images/tiledbackground6.png",
		"images/sprite14-sheet0.png",
		"images/d10-sheet0.png",
		"images/br25-sheet0.png",
		"images/b25-sheet0.png",
		"images/i25-sheet0.png",
		"images/d25-sheet0.png",
		"images/per1-sheet0.png",
		"images/sprite17-sheet0.png",
		"images/sobre-sheet0.png",
		"images/sprite21-sheet0.png",
		"images/sprite22-sheet0.png",
		"images/sprite22-sheet1.png",
		"images/p1-sheet0.png",
		"images/n1-sheet0.png",
		"images/sprite23-sheet0.png",
		"images/sprite25-sheet0.png",
		"images/pasintro-sheet0.png",
		"images/exerro-sheet0.png",
		"images/sprite15-sheet0.png",
		"images/exganhou-sheet0.png",
		"images/posa1-sheet0.png",
		"images/sprite36-sheet0.png",
		"images/tiledbackground7.png",
		"images/apresprojeto-sheet0.png",
		"images/tiledbackground9.png",
		"media/som bolha estourando.m4a",
		"media/som bolha estourando.ogg",
		"media/somjoguinhodabolha.ogg",
		"media/som drag botão.m4a",
		"media/som drag botão.ogg",
		"media/353206__rhodesmas__intro-01.m4a",
		"media/353206__rhodesmas__intro-01.ogg",
		"media/É a sua primeira vez aqui.ogg",
		"media/lembr se que basta estourar as bolhinhas.ogg",
		"media/basta clicar na bolhinha (mp3cut.net).m4a",
		"media/basta clicar na bolhinha (mp3cut.net).ogg",
		"media/parabens, concluiu os desafios.ogg",
		"media/parabens, notei que todas vamos a mais uma par (mp3cut.net).m4a",
		"media/parabens, notei que todas vamos a mais uma par (mp3cut.net).ogg",
		"media/o mundo flarc foi pensado (mp3cut.net).m4a",
		"media/o mundo flarc foi pensado (mp3cut.net).ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}